ENMN/Models/Message.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public int MessageThreadID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int OrderNo { get; set; }
        public string Text { get; set; }
        public int SenderID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual MessageThread MessageThread { get; set; }
    }
}

ENMN/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Text;
using System.IO;
using ENMN.Models;

namespace ENMN.Controllers
{
    public class MessagesController : Controller
    {
        private zpeterseEntities db = new zpeterseEntities();

        // GET: Messages
        public ActionResult Index(int ThreadID)
        {
            var messages = db.Messages.Include(m => m.Person).Include(m => m.MessageThread).Where(m => m.MessageThreadID == ThreadID).OrderBy(m=> m.OrderNo);
            return View(messages.ToList());
        }

        // GET: Messages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // GET: Messages/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.SenderID = new SelectList(db.People, "PersonID", "FirstName");
            ViewBag.MessageThreadID = new SelectList(db.MessageThreads, "MessageThreadID", "MessageThreadID");
            return PartialView("_CreatePartial", new ENMN.Models.Message());
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MessageID,MessageThreadID,DateTime,OrderNo,Text,SenderID")] Message message, DateTime dateTime, string senderID, string threadID)
        {
            int temp = 0;
            message.DateTime = dateTime;
            temp = Convert.ToInt32(senderID);
            message.SenderID = temp;
            temp = Convert.ToInt32(threadID);
            message.MessageThreadID = temp;
            zpeterseEntities dbc = new zpeterseEntities();
            message.OrderNo = dbc.Messages.Where(m=> m.MessageThreadID == temp).Count();
            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                db.SaveChanges();
                int t = dbc.MessageThreads.Where(m => m.MessageThreadID == message.MessageThreadID).First().MotherID;
                String id = dbc.People.Where(m => m.PersonID == t).First().GCMConnectionString;
                sendGCM(id, message.MessageID);
                return RedirectToAction("Index", new {@ThreadID = threadID});
            }

            ViewBag.SenderID = new SelectList(db.People, "PersonID", "FirstName", message.SenderID);
            ViewBag.MessageThreadID = new SelectList(db.MessageThreads, "MessageThreadID", "MessageThreadID", message.MessageThreadID);
            return Redirect("Messages?"+threadID);
            //return View(message);
        }

        // GET: Messages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            ViewBag.SenderID = new SelectList(db.People, "PersonID", "FirstName", message.SenderID);
            ViewBag.MessageThreadID = new SelectList(db.MessageThreads, "MessageThreadID", "MessageThreadID", message.MessageThreadID);
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MessageID,MessageThreadID,DateTime,OrderNo,Text,SenderID")] Message message)
        {
            if (ModelState.IsValid)
            {
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SenderID = new SelectList(db.People, "PersonID", "FirstName", message.SenderID);
            ViewBag.MessageThreadID = new SelectList(db.MessageThreads, "MessageThreadID", "MessageThreadID", message.MessageThreadID);
            return View(message);
        }

        // GET: Messages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        void sendGCM(string regId, int messageId)
        {
            var applicationID = "AIzaSyCb7ulAlp7e7lQQ_gjtiZvIB0FpjSm0IU8";


            var SENDER_ID = "763683898982";
            WebRequest tRequest;
            tRequest = WebRequest.Create("https://android.googleapis.com/gcm/send");
            tRequest.Method = "post";
            tRequest.ContentType = " application/x-www-form-urlencoded;charset=UTF-8";
            tRequest.Headers.Add(string.Format("Authorization: key={0}", applicationID));

            tRequest.Headers.Add(string.Format("Sender: id={0}", SENDER_ID));

            string postData = "collapse_key=score_update&time_to_live=108&delay_while_idle=1&data.message=" + messageId + "&data.time=" + System.DateTime.Now.ToString() + "&registration_id=" + regId + "";
            Console.WriteLine(postData);
            Byte[] byteArray = Encoding.UTF8.GetBytes(postData);
            tRequest.ContentLength = byteArray.Length;

            Stream dataStream = tRequest.GetRequestStream();
            dataStream.Write(byteArray, 0, byteArray.Length);
            dataStream.Close();

            WebResponse tResponse = tRequest.GetResponse();

            dataStream = tResponse.GetResponseStream();

            StreamReader tReader = new StreamReader(dataStream);

            String sResponseFromServer = tReader.ReadToEnd();

            tReader.Close();
            dataStream.Close();
            tResponse.Close();
        }
    }
}

ENMN/Views/Messages/Create.cshtml
@model ENMN.Models.Message

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MessageThreadID, "MessageThreadID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MessageThreadID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MessageThreadID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenderID, "SenderID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SenderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SenderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    @Html.ActionLink("Back to List", "Index", "Messages", new { @ThreadID = @Request.QueryString["ThreadID"] }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ENMN/Views/Messages/Delete.cshtml
@model ENMN.Models.Message

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MessageThread.MessageThreadID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MessageThread.MessageThreadID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ENMN/Views/Messages/Details.cshtml
@model ENMN.Models.Message

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MessageThread.MessageThreadID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MessageThread.MessageThreadID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MessageID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ENMN/Views/Messages/Edit.cshtml
@model ENMN.Models.Message

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MessageID)

        <div class="form-group">
            @Html.LabelFor(model => model.MessageThreadID, "MessageThreadID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MessageThreadID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MessageThreadID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenderID, "SenderID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SenderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SenderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ENMN/Views/Messages/Index.cshtml
@model IEnumerable<ENMN.Models.Message>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create", "Messages", new { @ThreadID = @Request.QueryString["ThreadID"] }, null)*@
    @*@Html.ActionLink("Create New", "Create", "Messages", new { @ThreadID = item.MessageThreadID }, null)*@
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.DateTime)*@
            Time
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.OrderNo)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.Person.FirstName)*@
            Sent By
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Text)*@
            Message
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.MessageThread.MessageThreadID)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateTime)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.OrderNo)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Person.FirstName)
            @Html.DisplayFor(modelItem => item.Person.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.MessageThread.MessageThreadID)
        </td>*@
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MessageID }) |
            @Html.ActionLink("Details", "Details", new { id=item.MessageID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MessageID })
        </td>*@
    </tr>
}

</table>
<div>
 @{Html.RenderAction("Create", "Messages");}
</div>
<div>
    @Html.ActionLink("Back to Message Threads", "Index", "MessageThreads")
</div>

ENMN/Views/Messages/_CreatePartial.cshtml
@model ENMN.Models.Message



@using (Html.BeginForm("Create", "Messages", new { senderID = Session["LoggedUserID"],  threadID = Request.QueryString["ThreadID"], dateTime = DateTime.Now }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reply or Send New Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" }, @cols = "120", @rows = "8" })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.MessageThreadID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MessageThreadID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MessageThreadID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenderID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SenderID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SenderID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@